### ISSUE TITLE
Change package name for Meta loader

### ISSUE THREAD

**Issue by rsjtdrjgfuzkfg** [GodotVR/godot_openxr_loaders#14]
I'd prefer to keep loaders in a shared package namespaces associated with the Godot game engine. As far as I can see, godot dot com does not belong to the project. If that is correct, could we change it to something within godotengine.org?

In #13 I proposed `org.godotengine.openxrloaders.pico` for Pico, which would lead to `org.godotengine.openxrloaders.meta`. That said, I'm open to other naming conventions.

**Comment by BastiaanOlij** [comment]
Yes, this makes sense to me.

**Comment by m4gr3d** [comment]
Addressed by #15
