### ISSUE TITLE
godot 4 beta 8 and pico 4 not working anymore

### ISSUE THREAD

**Issue by flobotics** [GodotVR/godot_openxr_loaders#16]
hi,
when i copy GodotOpenXRPico.gdap into my projects android/plugins/ folder it returns 

`  modules/gdscript/gdscript_analyzer.cpp:670 - Parser bug (please report): tried to assign unset node without an identifier.`

I have no option to enable "godot openxr pico" anymore in Project->Export view ?

when i build the apk and run it on device , it shows a black screen in "not VR-mode" .

**Comment by rsjtdrjgfuzkfg** [comment]
Works for me, I'd assume there is something in the specific project you're trying to build. Maybe try [the demo scene](https://github.com/BastiaanOlij/godot4_openxr_demo) to see if the issue persists?

**Comment by flobotics** [comment]
i created a new project with beta-8 and it prints

`Invalid plugin config file GodotOpenXRPico.gdap`

But it works, sorry seemed a bug in my previous project.

thx

**Comment by rsjtdrjgfuzkfg** [comment]
As this issue is identified to not be in this repository, we should imho close it.

[Ping to @BastiaanOlij as I know he has the powers to close issues, not sure who else has the permission to do so]

**Comment by BastiaanOlij** [comment]
@m4gr3d and @kisg at the moment, happy to add you too Dirk, just sent me an email if you want to become one of the maintainers for this repo

And yes I'll close this issue. I generally don't like closing issues until the OP gives confirmation that an issue is fixed even if that means issues tend to go stale.
