### ISSUE TITLE
The APK in PICO not working

### ISSUE THREAD

**Issue by robherre** [GodotVR/godot_openxr_loaders#21]
I follow the instructions in the video:
https://www.youtube.com/watch?v=wDXnsy2IH1A
with Godot 4.0 Beta v16 and PICO 4 VR glasses.

It works with SteamVR and PICO Link (Streaming assistant), but when I export the project to Android (always following the instructions of the video it doesn't work.

After a few seconds loading the PICO glasses show a image with ground and "sky" and a second before closes.

If I do a Remote Debug Godot shows the message ("platform/windows/display_server_windows.cpp:1008 - Condition "!windows.has(p_window)" is true. Returning: Point2i()") 44 times or more.

**Comment by BastiaanOlij** [comment]
@robherre are you using the Vulkan renderer? We're still waiting on a driver update on the PICO so for now try if it works with the OpenGL renderer.

**Comment by robherre** [comment]
How I select the renderer in Godot 4.0? I'm using Mobile renderer both in main screen and in project settings.

**Comment by BastiaanOlij** [comment]
Thats likely the Vulkan renderer, you need to select compatibility from the dropdown in the top righthand corner:
![image](https://user-images.githubusercontent.com/1945449/215434753-da868fe7-6219-4158-bd4f-54e8b5eb1e9f.png)

**Comment by robherre** [comment]
It works! I can see the image now but the controllers not responding.

**Comment by BastiaanOlij** [comment]
> It works! I can see the image now but the controllers not responding.

Make sure to check with the new Godot beta that was just released. There were a bunch of export regressions introduced including one that broke the action map.

**Comment by robherre** [comment]
Nothing! With beta 17 no movement of controller either

**Comment by BastiaanOlij** [comment]
Now that I have a PICO I could test and indeed it seems to work nicely.
Even made a video about it :) https://youtu.be/ZckQ-6ocHrI
Closing this issue
