### ISSUE TITLE
godotlib...

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_openxr_loaders#4]
Right now I've included a copy of the godotlib aar from the Godot 4 beta. I'm wondering if it makes more sense to just wget this file in the CI script from the official Godot site (i.e. https://downloads.tuxfamily.org/godotengine/4.0/beta1/)

**Comment by rsjtdrjgfuzkfg** [comment]
I made a proposal in #13 – Imho we do not need the lib at all. If you insist on keeping it, we could re-add it as part of the :godot-lib subproject so it can be managed centrally, for all loaders at once.

**Comment by rsjtdrjgfuzkfg** [comment]
@BastiaanOlij I think this can get closed, as #13 replaced the aar with a maven dependency.
