### ISSUE TITLE
Combine all loaders in a single repo?

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_openxr_loaders#6]
One of the suggestions made was to combine all the loaders in one repo? That would mean renaming this repo to `godot_openxr_loaders` and altering the scripts so we build multiple AARs, one for meta, one for khronos, potentially one for PICO?

Then this can be uploaded as a loader pack to the asset library and users can just enable/disable them.

**Comment by BastiaanOlij** [comment]
Result of discussion on Godot chat is to combine the loaders in a single repo. We're updating this repo to indicate this. Currently only the meta loader is present but others will be added soon

**Comment by rsjtdrjgfuzkfg** [comment]
Could we also place all aar files in a shared folder? I think this would simplify documentation and deployment:

    android
    \- plugins
       |-GodotOpenXRMeta.gdap
       |-GodotOpenXRPico.gdap
       \-godotopenxr  (or GodotOpenXR for consistency?)
         |-godotopenxrmeta-debug.aar (or -release, we don't need both; I'd prefer the latter)
         \-godotopenxrpico-release.aar

**Comment by BastiaanOlij** [comment]
We've followed through with this and are slowly building this out.
